version: '3.4'

services:
  # mammam-backend:
  #   image: mammam-backend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5434/web
  #     NODE_ENV: development
  #     PORT: 3000
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   command: npm run dev
  #   volumes:
  #     - .src:/app/src

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"
  #   volumes:
  #     - .docker/redis:/data
  #   restart: always

  postgres:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web