version: '3.4'

services:
  mammam-backend:
    image: mammam-backend
    container_name: mammam-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ./:/app/

  redis:
    image: redis:latest
    container_name: caching
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - .docker/redis:/data
    restart: always

  postgres:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mammam