version: '3.4'

services:
  mammam-backend:
    image: mammam-backend
    container_name: mammam-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    depends_on:
      - postgres
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 3000:3000
    command: sh -c "npm i --no-optional && npm i -g sequelize-cli && sequelize db:migrate && npm start"
    volumes:
      - ./:/app/
    restart: always

  redis:
    image: redis:latest
    container_name: caching
    ports:
      - "6379:6379"
    volumes:
      - .docker/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

  postgres:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mammam
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9300:9300
      - 9200:9200
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.0.1
  #   container_name: kibana
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  # redis-commander:
  #   container_name: redis-commander
  #   image: rediscommander/redis-commander
  #   restart: always
  #   environment:
  #     - REDIS_HOSTS=redis
  #   ports:
  #     - "8081:8081"
  # proxy:
  #   image: nginx:alpine
  #   container_name: web-proxy
  #   restart: unless-stopped
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/conf.d/default.conf
  #     - ./mammam_me_chain.crt:/etc/ssl/mammam_me_chain.crt
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - mammam-backend
volumes:
  esdata: